"""Add hosted zone database model

Revision ID: 7daf71a08e47
Revises: ad7148b40055
Create Date: 2026-08-13 20:30:02.541719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7daf71a08e47'
down_revision: Union[str, Sequence[str], None] = 'ad7148b40055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosted_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosted_zones_id'), 'hosted_zones', ['id'], unique=False)
    op.create_index(op.f('ix_hosted_zones_name'), 'hosted_zones', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hosted_zones_name'), table_name='hosted_zones')
    op.drop_index(op.f('ix_hosted_zones_id'), table_name='hosted_zones')
    op.drop_table('hosted_zones')
    # ### end Alembic commands ###
