"""Add DNS record database model

Revision ID: e62509c48be0
Revises: 7daf71a08e47
Create Date: 2026-08-13 20:36:11.470837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62509c48be0'
down_revision: Union[str, Sequence[str], None] = '7daf71a08e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hosted_zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('routing_policy', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hosted_zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_records_id'), 'dns_records', ['id'], unique=False)
    op.create_index(op.f('ix_dns_records_name'), 'dns_records', ['name'], unique=False)
    op.create_index(op.f('ix_dns_records_type'), 'dns_records', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dns_records_type'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_name'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_id'), table_name='dns_records')
    op.drop_table('dns_records')
    # ### end Alembic commands ###
